# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '3ed2d37d-d668-4151-8292-6bd0a04021c5'
  imageRepository: 'customemyproject'
  containerRegistry: 'myacrddemo.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:

    - task: Maven@1
      displayName: 'Maven Package'
      inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean package'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.17'
            mavenOptions: '-Xmx1024m'
            publishJUnitResults: false


    - task: Docker@2
      inputs:
        containerRegistry: 'docker-registory'
        repository: 'testing-project'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

    