# Starter pipeline
# Stage-1
 #Task1: Build jar file
 #Task2: Build docker image and push to ACR 
 #Task3: copy manifest files to build artifact directory
 #Task4: publish build artifacts to auzre pipelines
 # pipeline hierarchial flow: stage - stage - jobs - job - steps - task1, task2, task3

trigger:
- master

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        displayName: Build job
        pool:
         vmImage: 'ubuntu-latest'
        steps:
        - task: Maven@1
          inputs:
           mavenPomFile: 'pom.xml'
           goals: 'clean package'
           publishJUnitResults: false
           javaHomeOption: 'JDKVersion'
           jdkVersionOption: '1.17'
           mavenVersionOption: 'Default'
           mavenAuthenticateFeed: true
           sonarQubeRunAnalysis: false

        - task: Docker@2
          inputs:
            containerRegistry: 'manual-aks-conn'
            repository: 'custome-myproject2'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'

        ## push artifacts pipeline code in addition to build and push
        - bash: echo Contents in System Default Working Directory; ls -R $(System.DefaultWorkingDirectory)
        - bash: echo Before copying Contents in Build Artifact Directory; ls -R $(Build.ArtifactStagingDirectory)
    # Task-2 Copy files (Copy files from a source folder to target folder)
    # Source Directory: $(System.DefaultWorkingDirectory)/kube-manifests
    # Target Directory: $(Build.ArtifactStagingDirectory)

        - task: CopyFiles@2
          inputs:
           SourceFolder: '$(System.DefaultWorkingDirectory)/manifests'
           Contents: '**'
           TargetFolder: '$(Build.ArtifactStagingDirectory)'
        # Task-3 publish build artifacts (publish build to azre pipeline)

              # Task-3 publish build artifacts (publish build to azre pipeline)

        - task: PublishBuildArtifacts@1
          inputs:
           PathtoPublish: '$(Build.ArtifactStagingDirectory)'
           ArtifactName: 'kube-manifests'
           publishLocation: 'Container'