

variables:
 - group: acr-auth-group  # Name of your Azure DevOps Variable Group

 
trigger:
 -none
 
pool:
 vmImage: ubuntu-latest
 
stages:
 - stage: Build
   jobs: 
    - job: Buildproject
      steps: 
       - task: Maven@3
         inputes: 
           mavenPomFile: 'pom.xml'
           mavenOptions: '-Xmx3072m'
           javaHomeOption: 'JDKVersion'
           jdkVersionOption: '17'
           jdkArchitectureOption: 'x64'
           publishJUnitResults: true
           testResultsFiles: '**/surefire-reports/TEST-*.xml'
           goals: 'compile jib:build -Djib.to.auth.username=$(username) -Djib.to.auth.password=$(password)'
           
 - stage: Deploy
   dependsOn: Build
   jobs: 
     - job: kubernetes_deploy
       steps: 
         - task: Kubernetes@0
           displayName: 'kubectl deleted pods if exists'
           inputs: 
             kubernetesServiceConnection: aksconn
             command: delete
             arguments: ' pods aksacr --ignore-not-found=true'
         - task: Kubernetes@0
           displayName: 'kubectl delete service if exists'
           inputs: 
             kubernetesServiceConnection: aksconn
             command: delete
             arguments: 'svc aksacr --ignore-not-found=true '
         - task: Kubernetes@0
           displayName: 'kubectl delete service if exists'
           inputs: 
             kubernetesServiceConnection: aksconn
             command: run
             arguments: 'aksacr --image =myacrrepo1234.azurecr.io/nikit12345/testing:latest'
             
         - task: Kubernetes@0
           displayName: 'kubectl expose'
           inputs: 
             kubernetesServiceConnection: aksconn
             command: expose
             arguments: 'pods aksacr --type=LoadBalancer --port=90 --target-port=9090'
