apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      containers:
      - name: testing-container
        image: nikitamane/testing:v4
        
        ports:
        - containerPort: 7575
---
apiVersion: v1
kind: Service
metadata:
  name: testing
spec:
  type: LoadBalancer
  selector:
    app: testing
  ports:
    - protocol: TCP
      port: 7575
      targetPort: 7575
