apiVersion : apps/v1
kind: Deployment
metadata:
  name: testing-project 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing-project
  template:
    metadata:
      labels:
        app: testing-project 
    spec:
      containers:
        - name: testing-project 
          image: myacrddemo.azurecr.io/customemyproject
          ports:
          - containerPort: 7575
          
