apiVersion: v1
kind: Service
metadata:
  name: testingmyproject
spec:
  type: LoadBalancer
  selector:
    app: testingmyproject
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7575
  
